version: 0.0
os: linux
files:
  - source: /
    destination: /var/hello_world
hooks:
  BeforeInstall:
    - location: shScripts/cleanup.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: shScripts/dependencies.sh
      timeout: 180
      runas: root
    - location: shScripts/runApp.sh
      timeout: 180
      runas: root